### PR TITLE
Templating ERC721 & Handling some known failures in IPFS.cat

### LINKED ISSUE #3: Erc721 tokens not showing on account
Problem:
The account 0x862Bd4208b2F6ed64Ce92AAdA2669d3c5CC705d9 has one Cozy Cosmonauts NFT but it doesn't appear on the subgraph.

The subgraph isn't indexing the NFTs correctly, it should pick up all NFTs provided the tokenURI of the NFT is a valid http url or a valid ipfs url

Resources:
[cozy cosmonauts nft](https://explorer.fuse.io/address/0x32319834d90323127988E4e2DC7b2162d4262904/transactions)
[fuse nft subgraph](https://thegraph.com/hosted-service/subgraph/fuseio/fuse-nft)

### PR DESCRIPTION
**Pull request by GundamDweeb**
Hi All,

Kent from Graphrica.

Major changes in this branch:

1. Templating ERC721 - This indexes each contract seperately, and allows a bit more flexibility if other handlers need to be added. See `Erc721.create(contractAddress)`. This should also speed up indexing/syncing.
2. IPFS is deprecated and is known to fail with timeouts.
3. I did make an attempt to parse some base64 json into json - this is a work in progress and I hope to solve this with some internal teams.
4. CozyCosmonauts cause IPFS to fail, I just save the URI and skip the reading of metadata. We can work on this.

@leonprou @mul53 

fixes #3 :

See here for testing:
https://thegraph.com/hosted-service/subgraph/gundamdweeb/fuse-network-erc721?query=Account%20with%20Cozy

### CODE REVIEW

**Comment by GundamDweeb** [comment]
@mul53 

Here is some of the tasks and known issues I was working with:

# Fuse Network ERC721

#### Tasks:

- [ ] Remove Account with 0 balance
- [ ] Check for exceptions
- [ ] FIGURE OUT HOW TO PARSE THAT BASE64
- [x] Cover URI Update


https://github.com/fuseio/fuse-nft-subgraph/pull/4

13085303 - Last Block Failure -
14149632 - Last Block Failure - 0x876b6d93c27aee580ad492267200c6ce30228f8dbedbaddda0a064d2c92a27e8
14 149 632


https://explorer.fuse.io/tx/0x63be68eaf3607404a3ae900f4969ca0ad51838465c50976d877e7ca9627cb4ef/token-transfers

### Current Issues:


https://thegraph.com/hosted-service/subgraph/gundamdweeb/fuse-network-erc721?query=IPFS%20Failures

### IPFS Failures to check


- [x] **0xaa8c1b2cf1005eb30f5d5c1cef2efc540ac49bbd**
    - IPFS is broken
- [ ] **0xa9c476274be91fcc920ab53436ed563f5723f2d1**
    - Is JSON - we can perhaps parse it

**Comment by GundamDweeb** [comment]
I have removed the escape from readMetadata for Cozy Collection - 

Let's see how it deals with the IPFS!

**Comment by GundamDweeb** [comment]
Here is a Pending version of Fix - https://thegraph.com/hosted-service/subgraph/gundamdweeb/fuse-network-erc721?version=pending

**Comment by GundamDweeb** [comment]
So by removing the Cozy Check -  it fails once again at the same block mentioned above on that tx. I am pushing a version that just skips that first ID in cozy. https://thegraph.com/hosted-service/subgraph/gundamdweeb/fuse-network-erc721?version=pending

**Comment by leonprou** [comment]
Hey @GundamDweeb ,
Thanks for the PR 👍 
About the Cozy issues, can you give more details? Cozy is a top project so we need it to be included

**Comment by GundamDweeb** [comment]
Hi @leonprou 

This PR is being closed.

**Pull request closed without merging**
