### PR TITLE
feat(cozyCosmonauts): fixed get Cosmonauts NFT Image #3

### LINKED ISSUE #3: Erc721 tokens not showing on account
Problem:
The account 0x862Bd4208b2F6ed64Ce92AAdA2669d3c5CC705d9 has one Cozy Cosmonauts NFT but it doesn't appear on the subgraph.

The subgraph isn't indexing the NFTs correctly, it should pick up all NFTs provided the tokenURI of the NFT is a valid http url or a valid ipfs url

Resources:
[cozy cosmonauts nft](https://explorer.fuse.io/address/0x32319834d90323127988E4e2DC7b2162d4262904/transactions)
[fuse nft subgraph](https://thegraph.com/hosted-service/subgraph/fuseio/fuse-nft)

### PR DESCRIPTION
**Pull request by developerfred**
close #3 

ref: https://bafybeid64tyd25ovegjakaq6qyjyo332qzeqj3md6lygqgjg6aj5u5gybi.ipfs.dweb.link/215.png

The Graph: https://thegraph.com/hosted-service/subgraph/developerfred/fuse-nft-codingsh

in the future add pinata -> https://gateway.pinata.cloud/ipfs/

### CODE REVIEW

**Comment by mul53** [comment]
@developerfred why don't we use https://ipfs.io/ipfs/QmWszZ58xf9avo6pV7WWpwa6vzT7tpGfTX3SNGEayxqBc5/215.png instead of https://bafybeid64tyd25ovegjakaq6qyjyo332qzeqj3md6lygqgjg6aj5u5gybi.ipfs.dweb.link/215.png

**Comment by developerfred** [comment]
> @developerfred why don't we use [ipfs.io/ipfs/QmWszZ58xf9avo6pV7WWpwa6vzT7tpGfTX3SNGEayxqBc5/215.png](https://ipfs.io/ipfs/QmWszZ58xf9avo6pV7WWpwa6vzT7tpGfTX3SNGEayxqBc5/215.png) instead of [bafybeid64tyd25ovegjakaq6qyjyo332qzeqj3md6lygqgjg6aj5u5gybi.ipfs.dweb.link/215.png](https://bafybeid64tyd25ovegjakaq6qyjyo332qzeqj3md6lygqgjg6aj5u5gybi.ipfs.dweb.link/215.png)
> 
> The subgraph doesn't seem to be indexing properly maybe checking that first

the delivery bafybeid64tyd25ovegjakaq6qyjyo332qzeqj3md6lygqgjg6aj5u5gybi.ipfs.dweb.link speed is faster. 
but i can change if needed

**Comment by developerfred** [comment]
@mul53 I'm going to need to explore more I don't understand why my subgraph doesn't index, the price stays at 80% and it doesn't give an error either

**Comment by developerfred** [comment]
> @mul53 I'm going to need to explore more I don't understand why my subgraph doesn't index, the price stays at 80% and it doesn't give an error either

@mul53 it's syncing but it's slow, I'll see if it's at 100% today

**Comment by developerfred** [comment]
> > @mul53 I'm going to need to explore more I don't understand why my subgraph doesn't index, the price stays at 80% and it doesn't give an error either
> 
> @mul53 it's syncing but it's slow, I'll see if it's at 100% today

@mul53 I believe there are few nodes connected in the subgraph so it is very slow, but we still have no errors.

**Comment by developerfred** [comment]
Breakpoint ref: https://gist.github.com/developerfred/abf58874e84c78f49a80881e37456998

**Comment by leonprou** [comment]
Hey @developerfred , is the fix only for cozy?

**Comment by developerfred** [comment]
> Hey @developerfred , is the fix only for cozy?

No, now they can get all the nfts now.
for cozy I just change the ipfs address

**Comment by mul53** [comment]
> > @developerfred why don't we use [ipfs.io/ipfs/QmWszZ58xf9avo6pV7WWpwa6vzT7tpGfTX3SNGEayxqBc5/215.png](https://ipfs.io/ipfs/QmWszZ58xf9avo6pV7WWpwa6vzT7tpGfTX3SNGEayxqBc5/215.png) instead of [bafybeid64tyd25ovegjakaq6qyjyo332qzeqj3md6lygqgjg6aj5u5gybi.ipfs.dweb.link/215.png](https://bafybeid64tyd25ovegjakaq6qyjyo332qzeqj3md6lygqgjg6aj5u5gybi.ipfs.dweb.link/215.png)
> > The subgraph doesn't seem to be indexing properly maybe checking that first
> 
> the delivery bafybeid64tyd25ovegjakaq6qyjyo332qzeqj3md6lygqgjg6aj5u5gybi.ipfs.dweb.link speed is faster. but i can change if needed

I still don't understand why we need to specifically add this for cozy, if it's the speed preventing it from indexing properly maybe it's better to use that for delivery for all. The subgraph has less entities than our subgraph https://thegraph.com/hosted-service/subgraph/fuseio/fuse-nft

**Comment by leonprou** [comment]
hey @mul53, thanks for your feedback on this!

I'm gonna write here an answer from thegraph team about the slowness:

```
Indexing here is only slow due to the mapping structure. This particular example does multiple ETH Calls and even an IPFS look up on every transfer. ETH calls should be reduced as much as possible and other parts can be streamlined as well to speed things up.
https://github.com/fuseio/fuse-nft-subgraph/blob/master/src/mapping.ts#L15

[mapping.ts](https://github.com/fuseio/fuse-nft-subgraph/blob/master/src/mapping.ts)
  let tokenURIResult = erc721Token.try_tokenURI(event.params.tokenId)
  ```

Looks like no need to fetch the tokenURI on each transfer - enough is doing so on the mints

**Comment by developerfred** [comment]
@leonprou and @mul53 I have two questions, one about the pre-defined schema of the subgraph, can the collection schema be replaced? or is it used by many dapps?

Second question is about the solution proposed by @leonprou to make the mint tracker, some contracts have the custom Mint function, for example suppose I have a codingsh collection my mint function would be mintCodingsh. I don't know what would be a good practice to capture this event. It would be awesome if you could help me with this.

On the other hand, I'm thinking and researching new ways to store the tokenURI in the subgraph and reduce the number of requests. This is my current working state.

**Pull request closed without merging**
